<?php

namespace app\modules\web\controllers;

use app\models\db\BCertificate;
use app\models\db\BUserbaseinfo;
use app\models\db\EStudentcertificate;
use yii\web\Controller;

/**
 * Default controller for the `web` module
 */
class StudentController extends BaseController
{
    public function beforeAction($action)
    {
        if(empty(\Yii::$app->session->get('iUserID'))){ //验证登录状态

            header('location:index.php?r=web/site/login');
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    /**
     * Renders the index view for the module
     * @return string
     * 证书管理
     */
    public function actionStudentcertificateindex()
    {
        /*
         * 获取所有证书
         * */
        $studentcertificate = EStudentcertificate::getStudentcertificate([EStudentcertificate::tableName().'.iUserID' => $this->userid]);

        return $this->renderPartial('studentcertificateindex',['cate'=>$studentcertificate]);
    }
    /**
     * Renders the index view for the module
     * @return string
     * 证书管理-详情
     */
    public function actionStudentcertificateinfo()
    {
        /*
         * 获取证书详情
         * */
        $id = \Yii::$app->request->get('id');
        if(!$id)
        {
            self::getFailInfo('参数错误',$this->method);
        }

        $studentcertificate = EStudentcertificate::getStudentcertificate([EStudentcertificate::tableName().'id' => $id])[0];

        if(!$studentcertificate)
        {
            self::getFailInfo('参数错误',$this->method);
        }

        return $this->render('studentcertificateinfo');

    }
    /**
     * Renders the index view for the module
     * @return string
     * 证书管理 - 编辑
     */
    public function actionStudentcertificateedit()
    {
        $cate = [];
        if(\Yii::$app->request->isPost)
        {
            $post = \Yii::$app->request->post();
            if(empty($post))
            {
                self::getFailInfo('证书名称不得为空',$this->method);
            }

            if(\Yii::$app->request->post('id'))
            {
                //每次编辑都得审核
                $post['status'] = EStudentcertificate::UNDERREVIEW;
                //编辑
                if(false == EStudentcertificate::updateStudentcertificate($post))
                {
                    self::getFailInfo('证书编辑失败',$this->method);
                }
            }else{
                //添加
                if(false == EStudentcertificate::insertStudentcertificate($post))
                {
                    self::getFailInfo('证书添加失败',$this->method);
                }
            }

            self::getSucInfo(['ok'=>true],$this->method);
        }else{

            $id = \Yii::$app->request->get('id');
            if ($id)
            {
                $cate = EStudentcertificate::findOne($id);
                if(!$cate)
                {
                    self::getFailInfo('参数错误',$this->method);
                }
            }
        }
        //获取证书类别
        $certificate = BCertificate::find()->orderBy('id desc')->all();
        $dBeginTime = date('Y-m-d 23:59:59');
        return $this->renderPartial('studentcertificateedit',['cate'=>$cate,'certificate'=>$certificate,'dBeginTime'=>$dBeginTime]);
    }
}
